### ISSUE TITLE
No Documentation

### ISSUE THREAD

**Issue by scalenderFilament** [CreateJS/CreateJS#1]
https://createjs.com/docs says there is supposed to be documentation here 

first line of createjs.js says

Visit http://createjs.com/ for documentation, updates and examples.

Can someone host documentation?

**Comment by tehvgg** [comment]
The links on https://createjs.com/docs will take you to the documentation for each library.

https://createjs.com/docs/easeljs
https://createjs.com/docs/tweenjs
https://createjs.com/docs/soundjs
https://createjs.com/docs/preloadjs
