### ISSUE TITLE
createjs.com certificate seems to have expired

### ISSUE THREAD

**Issue by jfred1979** [CreateJS/CreateJS#13]
The certificate for createjs.com appears to have expired, causing browser warnings when navigating to the site.

**Comment by C-Ezra-M** [comment]
<details>
<summary>Certificate information</summary>

![Certificate info](https://github.com/CreateJS/CreateJS/assets/70766223/77160ede-d0f3-45c7-8f72-0a3be2118f10)
</details>
The certificate expired on August 6, so that's a bit more than 2 weeks ago.

**Comment by WidgetKing** [comment]
Having the same problem. Would be really great to access the documentation right now!

**Comment by Nezteb** [comment]
cc @gskinner @wdamien @lannymcnie @tehvgg (Sorry for pings, I just wanted to make sure y'all were aware 💙)

**Comment by wdamien** [comment]
https is working again.
